# NOTE : requirements: 
# 	o lemon graph library
# 	o a recent compiler (c++11) support

CPPFLAGS=-O3 -g -std=c++11 -Wall #-fdiagnostics-color=auto 
#CPPFLAGS+=-DHASLEMON
#CPPFLAGS+=-fopenmp 
LDLIBS=-lm -lfftw3

fft_1d: fft_1d.cpp

clean:
	rm -f fft_1d
